/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/evaluator/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Program */
        post: operations["evaluate_program_evaluator__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * COMMAND_TYPE
         * @enum {integer}
         */
        COMMAND_TYPE: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;
        /** CommandLogEntry */
        CommandLogEntry: {
            recordType: components["schemas"]["RECORD_TYPE"];
            commandType: components["schemas"]["COMMAND_TYPE"];
            varType: components["schemas"]["VAR_TYPE"];
            /** Var */
            var: string | null;
            /** Value */
            value: unknown;
            /** Index */
            index: number;
        };
        /**
         * HINT_TYPE
         * @enum {integer}
         */
        HINT_TYPE: 1 | 2;
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HintLogEntry */
        HintLogEntry: {
            recordType: components["schemas"]["RECORD_TYPE"];
            hintType: components["schemas"]["HINT_TYPE"];
            /** Target */
            target: string | null;
            /** Values */
            values: unknown[];
        };
        /** ProgramInput */
        ProgramInput: {
            /** Program */
            program: string;
        };
        /**
         * RECORD_TYPE
         * @enum {integer}
         */
        RECORD_TYPE: 1 | 2;
        /**
         * VAR_TYPE
         * @enum {integer}
         */
        VAR_TYPE: 1 | 2 | 3 | 4 | 5;
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    evaluate_program_evaluator__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandLogEntry"] | components["schemas"]["HintLogEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
}
